name: ci
on:
  push:
    branches:
      - master
      - dev
jobs:
  go_get:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.41.1

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.17

      - name: Check out code
        uses: actions/checkout@v3

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: make build-server

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.17

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: make test-race

      - name: Integration tests
        run: make start && make test-integration
